baseURL = "https://nemec.lu"
languageCode = "en-us"
title = "Lulu rants"
theme = "kiss"
copyright = ""
disqusShortname = ""
Paginate = 10
enableRobotsTXT = true
googleAnalytics = "UA-42667966-1"

[params.rss] # Adding this tag enables RSS feed
includeContent = true # Includes whole content in rss
authorName = "Lukas Nemec" # Author full name
authorEmail = "lu.nemec@gmail.com" # Author email

[params.info]
enableSocial = true
poweredby = true
related = true
homeTitle = "Lulu rants"

[params.social]
github = "lunemec"
twitter = "LukasNemec1"
rss = "index.xml"